# Generated by Django 4.2.8 on 2024-01-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="business_role",
            field=models.CharField(blank=True, max_length=255, verbose_name="Business Role"),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, max_length=255, verbose_name="Company"),
        ),
        migrations.AddField(
            model_name="user",
            name="industry",
            field=models.CharField(blank=True, max_length=255, verbose_name="Industry"),
        ),
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.JSONField(default=dict, verbose_name="Interests"),
        ),
    ]
