# Generated by Django 4.2.8 on 2024-01-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_business_role_user_company_user_industry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="business_role",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Business Role"),
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Company"),
        ),
        migrations.AlterField(
            model_name="user",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Industry"),
        ),
        migrations.AlterField(
            model_name="user",
            name="interests",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="Interests"),
        ),
    ]
