version: '3'

volumes:
  ctim_local_postgres_data: {}
  ctim_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/test_integration/django/Dockerfile
    image: ctim_test_integration_django
    container_name: ctim_test_integration_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    environment:
      DJANGO_USE_LOCAL_ENV: "true"
      DJANGO_ALLOWED_HOSTS: localhost,0.0.0.0,127.0.0.1
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ctim
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
      DATABASE_URL: "postgres://debug:debug@postgres:5432/ctim"
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_ENVIRONMENT: GithubCI
      SENTRY_TRACES_SAMPLE_RATE: 1.0
      USE_DOCKER: "yes"
      IPYTHONDIR: /app/.ipython
      REDIS_URL: redis://redis:6379/0
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ctim_production_postgres
    container_name: ctim_local_postgres
    volumes:
      - ctim_local_postgres_data:/var/lib/postgresql/data
      - ctim_local_postgres_data_backups:/backups
    environment:
      DJANGO_USE_LOCAL_ENV: "true"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ctim
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
      DATABASE_URL: "postgres://debug:debug@postgres:5432/ctim"
