# Generated by Django 4.2.8 on 2024-05-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(max_length=100)),
                ("goal", models.TextField()),
                ("backstory", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CrewModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agents", models.ManyToManyField(to="crew.agentmodel")),
            ],
        ),
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                ("expected_output", models.TextField()),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crew.agentmodel")),
            ],
        ),
        migrations.CreateModel(
            name="ExecutionResultModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=50)),
                ("result_data", models.TextField()),
                ("crew", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crew.crewmodel")),
            ],
        ),
        migrations.AddField(
            model_name="crewmodel",
            name="tasks",
            field=models.ManyToManyField(to="crew.taskmodel"),
        ),
    ]
