# Generated by Django 4.2.8 on 2024-05-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crew", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crewmodel",
            name="name",
            field=models.CharField(default="name", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="name",
            field=models.CharField(default="name", max_length=100),
            preserve_default=False,
        ),
    ]
