# Generated by Django 4.2.8 on 2024-06-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crew", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolRegistryModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("module_path", models.CharField(max_length=255)),
                ("method_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ToolModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registry",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crew.toolregistrymodel"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agentmodel",
            name="tools",
            field=models.ManyToManyField(to="crew.toolmodel"),
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="tools",
            field=models.ManyToManyField(to="crew.toolmodel"),
        ),
    ]
