# Generated by Django 4.2.8 on 2024-06-06 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crew", "0002_crewmodel_name_taskmodel_name"),
        ("crew", "0003_toolregistrymodel_created_at_and_more"),
    ]

    operations = []
