# Generated by Django 4.2.8 on 2023-12-26 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("captcha", models.BooleanField(default=False)),
                ("parser", models.BooleanField(default=False)),
                ("javascript_render", models.BooleanField(default=False)),
                ("meta", models.JSONField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="profiles", to="ctia.group"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fqdn", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=100)),
                ("version", models.IntegerField()),
                ("slug", models.URLField()),
                ("available", models.BooleanField()),
                ("delay", models.FloatField(blank=True, null=True)),
                ("updated", models.DateTimeField()),
                ("lastscrape", models.DateTimeField()),
                ("enabled", models.BooleanField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="locations", to="ctia.group"
                    ),
                ),
            ],
        ),
    ]
