# Generated by Django 4.2.8 on 2023-12-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="fqdn",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="location",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
