# Generated by Django 4.2.8 on 2023-12-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctia", "0002_alter_location_fqdn_alter_location_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="url",
            field=models.URLField(max_length=1000),
        ),
    ]
