# Generated by Django 4.2.8 on 2023-12-26 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ctia", "0003_alter_profile_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("discovered", models.DateTimeField()),
                ("description", models.TextField()),
                ("website", models.URLField()),
                ("published", models.DateTimeField()),
                ("url", models.URLField()),
                ("country", models.CharField(max_length=100)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ctia.group")),
            ],
        ),
    ]
