# Generated by Django 4.2.8 on 2023-12-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctia", "0004_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="url",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="post",
            name="website",
            field=models.URLField(max_length=1000),
        ),
    ]
