# Generated by Django 4.2.8 on 2024-01-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctia", "0005_alter_post_url_alter_post_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
