# Generated by Django 4.2.8 on 2024-01-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctia", "0007_alter_post_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
