# Generated by Django 4.2.8 on 2024-01-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ctia", "0009_channel_userprofile_message_media_channel_members_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_id", models.BigIntegerField(unique=True)),
                ("content", models.TextField()),
                ("date_posted", models.DateTimeField()),
                ("edit_date", models.DateTimeField(blank=True, null=True)),
                ("views", models.IntegerField(blank=True, null=True)),
                ("forwards", models.IntegerField(blank=True, null=True)),
                ("reply_count", models.IntegerField(default=0)),
                ("media_json", models.JSONField(blank=True, null=True)),
                ("entities_json", models.JSONField(blank=True, null=True)),
                ("message_url", models.URLField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="posts", to="ctia.channel"
                    ),
                ),
            ],
        ),
    ]
