# Generated by Django 4.2.8 on 2024-01-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctia", "0010_channelpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="last_processed_message_id",
            field=models.BigIntegerField(default=0),
        ),
    ]
