# Generated by Django 4.2.8 on 2024-01-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctia", "0013_remove_channel_last_processed_message_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedChannelPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel_post_data", models.JSONField()),
                ("error_message", models.TextField()),
                ("retry_count", models.IntegerField(default=0)),
                ("last_attempt_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="channel",
            name="is_being_processed",
            field=models.BooleanField(default=False),
        ),
    ]
