# Generated by Django 4.2.8 on 2024-01-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctia", "0014_failedchannelpost_channel_is_being_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelpost",
            name="message_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="channelpost",
            unique_together={("channel", "message_id")},
        ),
    ]
