# Generated by Django 4.2.8 on 2024-04-15 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ctia", "0015_alter_channelpost_message_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreatActor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("origin", models.CharField(max_length=100)),
                ("activity_period", models.CharField(max_length=100)),
                ("targets", models.TextField()),
                ("motivation", models.TextField()),
                ("notable_info", models.TextField()),
                ("observed_behavior", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                (
                    "threat_actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="risks", to="ctia.threatactor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelatedThreatGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "main_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_groups",
                        to="ctia.threatactor",
                    ),
                ),
                (
                    "related_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="ctia.threatactor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mitigation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                (
                    "threat_actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="mitigations", to="ctia.threatactor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CVE",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cve_id", models.CharField(max_length=15)),
                ("description", models.TextField()),
                ("exploited_vulnerabilities", models.TextField()),
                (
                    "threat_actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cves", to="ctia.threatactor"
                    ),
                ),
            ],
        ),
    ]
