# Generated by Django 4.2.8 on 2024-04-15 09:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ctia", "0016_threatactor_risk_relatedthreatgroup_mitigation_cve"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_channels",
                to="ctia.threatactor",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_groups",
                to="ctia.threatactor",
            ),
        ),
        migrations.AddField(
            model_name="threatactor",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="threatactor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
