# Generated by Django 4.2.8 on 2024-04-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctia", "0017_channel_owner_group_owner_threatactor_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedthreatgroup",
            name="relation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="threatactor",
            name="origin",
            field=models.TextField(),
        ),
    ]
