name: Update DO App Platform Configuration

on:
  push:
    paths:
      - 'compose/test_integration/digitalocean/spec.yaml'

jobs:
  update-do-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        run: |
          sudo snap install doctl

      - name: Authenticate with Digital Ocean
        run: |
          doctl auth init --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Update App Platform config
        run: |
          doctl apps update cd5fd967-97e8-4fff-a233-8d826d8dc434 --spec compose/test_integration/digitalocean/spec.yaml
